export const timezones = [
  { code: 'GMT', name: 'Greenwich Mean Time', relative: 'GMT' },
  { code: 'UTC', name: 'Universal Coordinated Time', relative: 'GMT' },
  { code: 'ECT', name: 'European Central Time', relative: 'GMT+1:00' },
  { code: 'EET', name: 'Eastern European Time', relative: 'GMT+2:00' },
  { code: 'ART', name: '(Arabic) Egypt Standard Time', relative: 'GMT+2:00' },
  { code: 'EAT', name: 'Eastern African Time', relative: 'GMT+3:00' },
  { code: 'MET', name: 'Middle East Time', relative: 'GMT+3:30' },
  { code: 'NET', name: 'Near East Time', relative: 'GMT+4:00' },
  { code: 'PLT', name: 'Pakistan Lahore Time', relative: 'GMT+5:00' },
  { code: 'IST', name: 'India Standard Time', relative: 'GMT+5:30' },
  { code: 'BST', name: 'Bangladesh Standard Time', relative: 'GMT+6:00' },
  { code: 'VST', name: 'Vietnam Standard Time', relative: 'GMT+7:00' },
  { code: 'CTT', name: 'China Taiwan Time', relative: 'GMT+8:00' },
  { code: 'JST', name: 'Japan Standard Time', relative: 'GMT+9:00' },
  { code: 'ACT', name: 'Australia Central Time', relative: 'GMT+9:30' },
  { code: 'AET', name: 'Australia Eastern Time', relative: 'GMT+10:00' },
  { code: 'SST', name: 'Solomon Standard Time', relative: 'GMT+11:00' },
  { code: 'NST', name: 'New Zealand Standard Time', relative: 'GMT+12:00' },
  { code: 'MIT', name: 'Midway Islands Time', relative: 'GMT-11:00' },
  { code: 'HST', name: 'Hawaii Standard Time', relative: 'GMT-10:00' },
  { code: 'AST', name: 'Alaska Standard Time', relative: 'GMT-9:00' },
  { code: 'PST', name: 'Pacific Standard Time', relative: 'GMT-8:00' },
  { code: 'PNT', name: 'Phoenix Standard Time', relative: 'GMT-7:00' },
  { code: 'MST', name: 'Mountain Standard Time', relative: 'GMT-7:00' },
  { code: 'CST', name: 'Central Standard Time', relative: 'GMT-6:00' },
  { code: 'EST', name: 'Eastern Standard Time', relative: 'GMT-5:00' },
  { code: 'IET', name: 'Indiana Eastern Standard Time', relative: 'GMT-5:00' },
  { code: 'PRT', name: 'Puerto Rico and US Virgin Islands Time', relative: 'GMT-4:00' },
  { code: 'CNT', name: 'Canada Newfoundland Time', relative: 'GMT-3:30' },
  { code: 'AGT', name: 'Argentina Standard Time', relative: 'GMT-3:00' },
  { code: 'BET', name: 'Brazil Eastern Time', relative: 'GMT-3:00' },
  { code: 'CAT', name: 'Central African Time', relative: 'GMT-1:00' },
] as const;
